name: CI Detox iOS

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 200

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v1

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && pod install && cd ..

    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn detox build e2e --configuration ios
    - run: yarn detox test e2e --configuration ios --cleanup --record-logs failing --record-videos failing --take-screenshots failing
    - run: pwd
    - run: ls -l
    
    - name: Archive test failure results
      uses: actions/upload-artifact@v2
      with:
          name: test-failures
          path: artifacts/
